# coding: utf-8

"""
    MangaDex API

    MangaDex is an ad-free manga reader offering high-quality images!  This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.  # Acceptable use policy  Usage of our services implies acceptance of the following: - You **MUST** credit us - You **MUST** credit scanlation groups if you offer the ability to read chapters - You **CANNOT** run ads or paid services on your website and/or apps  These may change at any time for any and no reason and it is up to you check for updates from time to time.  # Security issues  If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately. 

    The version of the OpenAPI document: 5.10.2
    Contact: support@mangadex.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mangadex_openapi.models.get_statistics_manga_uuid200_response import GetStatisticsMangaUuid200Response

class TestGetStatisticsMangaUuid200Response(unittest.TestCase):
    """GetStatisticsMangaUuid200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetStatisticsMangaUuid200Response:
        """Test GetStatisticsMangaUuid200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetStatisticsMangaUuid200Response`
        """
        model = GetStatisticsMangaUuid200Response()
        if include_optional:
            return GetStatisticsMangaUuid200Response(
                result = 'ok',
                statistics = {
                    'key' : mangadex_openapi.models.get_statistics_manga_uuid_200_response_statistics_value.get_statistics_manga_uuid_200_response_statistics_value(
                        comments = mangadex_openapi.models.statistics_details_comments.StatisticsDetailsComments(
                            thread_id = 1, 
                            replies_count = 0, ), 
                        rating = mangadex_openapi.models.get_statistics_manga_uuid_200_response_statistics_value_rating.get_statistics_manga_uuid_200_response_statistics_value_rating(
                            average = 1.337, 
                            bayesian = 1.337, 
                            distribution = mangadex_openapi.models.get_statistics_manga_uuid_200_response_statistics_value_rating_distribution.get_statistics_manga_uuid_200_response_statistics_value_rating_distribution(
                                1 = 56, 
                                2 = 56, 
                                3 = 56, 
                                4 = 56, 
                                5 = 56, 
                                6 = 56, 
                                7 = 56, 
                                8 = 56, 
                                9 = 56, 
                                10 = 56, ), ), 
                        follows = 56, )
                    }
            )
        else:
            return GetStatisticsMangaUuid200Response(
        )
        """

    def testGetStatisticsMangaUuid200Response(self):
        """Test GetStatisticsMangaUuid200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
