# coding: utf-8

"""
    MangaDex API

    MangaDex is an ad-free manga reader offering high-quality images!  This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.  # Acceptable use policy  Usage of our services implies acceptance of the following: - You **MUST** credit us - You **MUST** credit scanlation groups if you offer the ability to read chapters - You **CANNOT** run ads or paid services on your website and/or apps  These may change at any time for any and no reason and it is up to you check for updates from time to time.  # Security issues  If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately. 

    The version of the OpenAPI document: 5.10.2
    Contact: support@mangadex.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mangadex_openapi.api.scanlation_group_api import ScanlationGroupApi


class TestScanlationGroupApi(unittest.TestCase):
    """ScanlationGroupApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ScanlationGroupApi()

    def tearDown(self) -> None:
        pass

    def test_delete_group_id(self) -> None:
        """Test case for delete_group_id

        Delete Scanlation Group
        """
        pass

    def test_delete_group_id_follow(self) -> None:
        """Test case for delete_group_id_follow

        Unfollow Scanlation Group
        """
        pass

    def test_get_group_id(self) -> None:
        """Test case for get_group_id

        Get Scanlation Group
        """
        pass

    def test_get_search_group(self) -> None:
        """Test case for get_search_group

        Scanlation Group list
        """
        pass

    def test_post_group(self) -> None:
        """Test case for post_group

        Create Scanlation Group
        """
        pass

    def test_post_group_id_follow(self) -> None:
        """Test case for post_group_id_follow

        Follow Scanlation Group
        """
        pass

    def test_put_group_id(self) -> None:
        """Test case for put_group_id

        Update Scanlation Group
        """
        pass


if __name__ == '__main__':
    unittest.main()
