# coding: utf-8

"""
    MangaDex API

    MangaDex is an ad-free manga reader offering high-quality images!  This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.  # Acceptable use policy  Usage of our services implies acceptance of the following: - You **MUST** credit us - You **MUST** credit scanlation groups if you offer the ability to read chapters - You **CANNOT** run ads or paid services on your website and/or apps  These may change at any time for any and no reason and it is up to you check for updates from time to time.  # Security issues  If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately. 

    The version of the OpenAPI document: 5.10.2
    Contact: support@mangadex.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mangadex_openapi.models.put_upload_session_file200_response import PutUploadSessionFile200Response

class TestPutUploadSessionFile200Response(unittest.TestCase):
    """PutUploadSessionFile200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PutUploadSessionFile200Response:
        """Test PutUploadSessionFile200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PutUploadSessionFile200Response`
        """
        model = PutUploadSessionFile200Response()
        if include_optional:
            return PutUploadSessionFile200Response(
                result = 'ok',
                errors = [
                    mangadex_openapi.models.error.Error(
                        id = '', 
                        status = 56, 
                        title = '', 
                        detail = '', 
                        context = '', )
                    ],
                data = [
                    mangadex_openapi.models.upload_session_file.UploadSessionFile(
                        id = '', 
                        type = 'upload_session_file', 
                        attributes = mangadex_openapi.models.upload_session_file_attributes.UploadSessionFileAttributes(
                            original_file_name = '', 
                            file_hash = '', 
                            file_size = 1.337, 
                            mime_type = '', 
                            source = 'local', 
                            version = 1, ), )
                    ]
            )
        else:
            return PutUploadSessionFile200Response(
        )
        """

    def testPutUploadSessionFile200Response(self):
        """Test PutUploadSessionFile200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
