# coding: utf-8

"""
    MangaDex API

    MangaDex is an ad-free manga reader offering high-quality images!  This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.  # Acceptable use policy  Usage of our services implies acceptance of the following: - You **MUST** credit us - You **MUST** credit scanlation groups if you offer the ability to read chapters - You **CANNOT** run ads or paid services on your website and/or apps  These may change at any time for any and no reason and it is up to you check for updates from time to time.  # Security issues  If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately. 

    The version of the OpenAPI document: 5.10.2
    Contact: support@mangadex.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mangadex_openapi.api.custom_list_api import CustomListApi


class TestCustomListApi(unittest.TestCase):
    """CustomListApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CustomListApi()

    def tearDown(self) -> None:
        pass

    def test_delete_list_id(self) -> None:
        """Test case for delete_list_id

        Delete CustomList
        """
        pass

    def test_delete_manga_id_list_list_id(self) -> None:
        """Test case for delete_manga_id_list_list_id

        Remove Manga in CustomList
        """
        pass

    def test_follow_list_id(self) -> None:
        """Test case for follow_list_id

        Follow CustomList
        """
        pass

    def test_get_list_id(self) -> None:
        """Test case for get_list_id

        Get CustomList
        """
        pass

    def test_get_user_id_list(self) -> None:
        """Test case for get_user_id_list

        Get User's CustomList list
        """
        pass

    def test_get_user_list(self) -> None:
        """Test case for get_user_list

        Get logged User CustomList list
        """
        pass

    def test_post_list(self) -> None:
        """Test case for post_list

        Create CustomList
        """
        pass

    def test_post_manga_id_list_list_id(self) -> None:
        """Test case for post_manga_id_list_list_id

        Add Manga in CustomList
        """
        pass

    def test_put_list_id(self) -> None:
        """Test case for put_list_id

        Update CustomList
        """
        pass

    def test_unfollow_list_id(self) -> None:
        """Test case for unfollow_list_id

        Unfollow CustomList
        """
        pass


if __name__ == '__main__':
    unittest.main()
