# coding: utf-8

"""
    MangaDex API

    MangaDex is an ad-free manga reader offering high-quality images!  This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.  # Acceptable use policy  Usage of our services implies acceptance of the following: - You **MUST** credit us - You **MUST** credit scanlation groups if you offer the ability to read chapters - You **CANNOT** run ads or paid services on your website and/or apps  These may change at any time for any and no reason and it is up to you check for updates from time to time.  # Security issues  If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately. 

    The version of the OpenAPI document: 5.10.2
    Contact: support@mangadex.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class GetStatisticsMangaUuid200ResponseStatisticsValueRatingDistribution(BaseModel):
    """
    GetStatisticsMangaUuid200ResponseStatisticsValueRatingDistribution
    """ # noqa: E501
    var_1: Optional[StrictInt] = Field(default=None, alias="1")
    var_2: Optional[StrictInt] = Field(default=None, alias="2")
    var_3: Optional[StrictInt] = Field(default=None, alias="3")
    var_4: Optional[StrictInt] = Field(default=None, alias="4")
    var_5: Optional[StrictInt] = Field(default=None, alias="5")
    var_6: Optional[StrictInt] = Field(default=None, alias="6")
    var_7: Optional[StrictInt] = Field(default=None, alias="7")
    var_8: Optional[StrictInt] = Field(default=None, alias="8")
    var_9: Optional[StrictInt] = Field(default=None, alias="9")
    var_10: Optional[StrictInt] = Field(default=None, alias="10")
    __properties: ClassVar[List[str]] = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetStatisticsMangaUuid200ResponseStatisticsValueRatingDistribution from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetStatisticsMangaUuid200ResponseStatisticsValueRatingDistribution from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "1": obj.get("1"),
            "2": obj.get("2"),
            "3": obj.get("3"),
            "4": obj.get("4"),
            "5": obj.get("5"),
            "6": obj.get("6"),
            "7": obj.get("7"),
            "8": obj.get("8"),
            "9": obj.get("9"),
            "10": obj.get("10")
        })
        return _obj


